### ISSUE TITLE
Can not import NVActivityIndicatorView in Class

### ISSUE THREAD

**Issue by WaqarKhalid** [ninjaprox/NVActivityIndicatorView#108]
After installing via cocoapods and even manually I can not import file in my view controller class and error comes there when I try to add

**Comment by vitalii-tym** [comment]
@WaqarKhalid  If you did manual installation you don't have to import anything. Files are already in your project and are supposed to be included in Compile Sources in Build Phases (double-check if they are there). So just use it.

**Comment by ninjaprox** [comment]
@WaqarKhalid: And if you're using CocoaPods, make sure adding `import NVActivityIndicatorView` in files using the library as in [USAGE](https://github.com/ninjaprox/NVActivityIndicatorView#usage).

**Comment by WaqarKhalid** [comment]
I double checked.All files are added in the build phases and when I try to import them in any controller file then it gives me error.

**Comment by ninjaprox** [comment]
@WaqarKhalid: Please provide error for investigation.

**Comment by WaqarKhalid** [comment]
![screen shot 2017-01-16 at 9 47 56 am](https://cloud.githubusercontent.com/assets/22659056/21971291/fe5710f0-dbd0-11e6-8f2c-a60525a4f4db.png)
You can see that I have included all the files but it is giving me this error of 'No such module NVIndicatorView'

**Comment by ninjaprox** [comment]
@WaqarKhalid: If you use manual way, no need to `import NVActivityIndicatorView`, just use classes right away.

**Comment by WaqarKhalid** [comment]
It worked.Thanks

**Comment by bharath-kamath** [comment]
@ninjaprox I installed the Swift 4 branch via Cocoapods but I get the same error.
The header(and framework) Search path is empty, shouldn't there be an import for NVActivityIndicatorView.
> No such module 'NVActivityIndicatorView'

Edit: Tried running the Example app after pod install and get the same error.

**Comment by ninjaprox** [comment]
@bharath-kamath: Have you tried common resolutions for CocoaPods? Btw, are using Swift or ObjC in your project, what CocoaPods version, `Podfile`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bharath-kamath** [comment]
I'm using Swift and the CocoaPods version is 1.3.

**Comment by bharatbyan** [comment]
I'm having the same issue, unable to import the NVActivityIndicatorView. 

![screen shot 2018-08-19 at 4 23 49 pm](https://user-images.githubusercontent.com/3232787/44308077-53d62880-a3cc-11e8-8a4d-9774f072bfe1.png)

**Comment by vitalii-tym** [comment]
@111jaam , I had this issue too after I decided to move NVActivityIndicatorView from manual inclusion to cocoapods.
~~Here's how I fixed this: looked if there was any other target in `Build Phases > Target Dependencies` in my target settings. There was one, so I tried to add NVActivityIndicatorView for that one also, even though it wasn't using NVActivityIndicatorView. Since the dependency was an extension, I had to add it as `NVActivityIndicatorView/AppExtension`. In podfile it was:~~

```
target 'Send to JIRA' do
pod 'NVActivityIndicatorView/AppExtension'
end

```

That new target also had a small problem, it gave error 

> 'NVActivityIndicatorView' is unavailable: cannot find Swift declaration for this class

~~Found that the error can be fixed by setting `Build Active Architecture Only` to `NO` in pods target. Unfortunately we'll need to change it after each `pod install` until this is fixed in NVActivityIndicatorView.~~

<img width="1190" alt="screenshot 2019-01-12 21 05 46" src="https://user-images.githubusercontent.com/5410835/51077440-9831d000-16af-11e9-9c99-e680ece9211c.png">

... and I also had to set `Module` to `NVActivityIndicatorView` for all activity indicators in Interface Builder, otherwise it was crashing.

<img width="259" alt="screenshot 2019-01-12 21 32 43" src="https://user-images.githubusercontent.com/5410835/51077798-c9140400-16b3-11e9-8e02-14d7ff27fab6.png">

UPDATE: please see my comment below for better solutions.

**Comment by ninjaprox** [comment]
@vitalii-tym: I wonder if you could send over the sample project which has the issue. I want to investigate this since it's weird that I never encounter this issue when testing on my side.

**Comment by vitalii-tym** [comment]
@ninjaprox , sorry for the fake alarm. I've spent some more time analyzing my project and found that issues were in my project's settings. Since the project is old enough and I had some manually added libs, project settings were not fresh at all. The problems were:
1) resolved `Framework Search Path` wasn't getting its value from CocoaPods and continued to use values from my target instead. I've cleared my target's setting and added it back again (because I still have some manually added libs). This made the CocoaPods value to automatically populate and fix the `unable to import the NVActivityIndicatorView` error (which was also applicable to all other pods)
<img width="588" alt="screenshot 2019-01-22 13 28 32" src="https://user-images.githubusercontent.com/5410835/51532759-a6b77e80-1e49-11e9-982c-d5408628bed9.png">

2) cleaning all "only active architecture = NO" settings from my targets and relying on Xcode's default ones fixed the `'NVActivityIndicatorView' is unavailable: cannot find Swift declaration for this class` error.
<img width="511" alt="screenshot 2019-01-22 13 29 35" src="https://user-images.githubusercontent.com/5410835/51533036-66a4cb80-1e4a-11e9-8533-e98ad974472d.png">

So, the NVActivityIndicatorView is completely fine when installed via CocoaPods 👍  
If anyone has problems, should carefully check your own project settings and review solutions to common issues with CocoaPods first.
