### ISSUE TITLE
Add Custom Animation

### ISSUE THREAD

**Issue by abackys** [ninjaprox/NVActivityIndicatorView#120]
It would be nice to have ability to add your own `NVActivityIndicatorType` by conforming to Protocol and using this Protocol instead of `NVActivityIndicatorType`, that way we could implement our own activity indicators without need to fork and editing the library. Same would apply to `NVActivityIndicatorShape`.

Is there something what would block this approach? I could work on MR if you see no issues with this.

**Comment by ninjaprox** [comment]
@abackys: Actually, it has been initiated and discussed a few times ago, just not yet be an official release. You can refer to these issues #39, #42, #98 for more information. There is also the branch `features/custom-animation` already there. Public the `NVActivityIndicatorAnimationDelegate` so that user can create custom animation should be straightforward. However, to make it works seamlessly with the current `NVActivityIndicatorType`, it requires a bit work on redesigning the code. And if we do so, it would be great to public `NVActivityIndicatorShape` as well, then user can take advantage of these utilities to create simple animation with ease. I think these two things are the most blockers. Although, contribution, PR on this is more than welcome.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
