### ISSUE TITLE
Works once then crashes

### ISSUE THREAD

**Issue by TheSwiftyCoder** [ninjaprox/NVActivityIndicatorView#131]
Got a view controller that removes from super view once user taps a button. If I go back into the view controller it crashes. I've tested the view by removing NVActivityIndicator and the error is gone. Using swift 3 under Xcode 8.2.1

The view is also storyBoard.instantiateViewController - not sure if that may be related?

**Comment by ninjaprox** [comment]
@jesse-cohen: Could you provide some code snippet?

**Comment by TheSwiftyCoder** [comment]
Just the standard code used. Had an outlet which inherited NVActivityIndicator. Used stop animating and start animating as per documentation. The viewcontroller is removed by removeFromSuperview. When recreating the view again NVActivityIndicator causes a crash.

**Comment by ninjaprox** [comment]
@jesse-cohen: I guess it's caused by the outlet. Usually the outlet is `weak` and implicit unwrapped optional (if you're using Swift). When calling `removeFromSuperview`, the outlet will become `nil`, then adding it again will cause crash. You can try making the outlet strong which is actually not recommended, then see if it works. Let me know if this helps.

**Comment by TheSwiftyCoder** [comment]
Thanks, Any way I can solve this without using a strong reference, say adding a UIView programatically?

**Comment by ninjaprox** [comment]
@jesse-cohen: That should be the correct way 👍. Btw, on call `stopAnimating`, the view is hidden, then `startAnimating` will show it so you don't need to remove and add it again if you're using `IBOutlet`.
