### ISSUE TITLE
Enable Nav bar during UIBlocker

### ISSUE THREAD

**Issue by justindunn** [ninjaprox/NVActivityIndicatorView#155]
Is there a way to keep the Navbar active on one view while activityindicator is loading? I have a page where I want the activity to show loading when a person logs into a video session but I want them to be able to hit the back in the nav bar if they decide to stop waiting, thanks in advance for any help!

**Comment by ninjaprox** [comment]
@justindunn: In that case, I think you should create a view container and an `NVActivityIndicatorView`, then add them to the view hierarchy instead of using UI blocker, so that you have more control of those (position, size).

**Comment by justindunn** [comment]
Ok that makes sense, but how would you disable the UI blocker?

**Comment by ninjaprox** [comment]
If you're talking of the built-in UI blocker, you can use `stopAnimating()`, otherwise just remove the view container you created.

**Comment by justindunn** [comment]
Ok but is there a way to keep the loading animating while disabling the built in UI blocker?

**Comment by ninjaprox** [comment]
I'm afraid not since the UI blocker contains the loading animation. Then when the UI blocker disappears, it's weird to keep the animation (if I get you correctly). In your case, I think what you want to do is to create a view container with the animation as a child, position it right below the navigation bar and size it to cover the rest area.

**Comment by justindunn** [comment]
Ok thanks for all your help! I'm going to try this out!
