### ISSUE TITLE
Improvements needed: code switfy, readability, more customizations 

### ISSUE THREAD

**Issue by lurui1029** [ninjaprox/NVActivityIndicatorView#267]
#### 1. Naming

All the static vars in `NVActivityIndicatorView` are named in FULL_UPPERCASE, such as:
```
public static var DEFAULT_TYPE: NVActivityIndicatorType = .ballSpinFadeLoader
```
According to [API Design Guidelines](https://swift.org/documentation/#migration-guides), a better way can be:
```
public static var defaultType: NVActivityIndicatorType = .ballSpinFadeLoader
```

#### 2. Positions
Many of static vars in `NVActivityIndicatorView.swift` are not used by `NVActivityIndicatorView ` itself, such as:
```
public static var DEFAULT_BLOCKER_SIZE = CGSize(width: 60, height: 60)
```
Move these vars to `NVActivityIndicatorPresenter.swift`or `NVActivityIndicatorViewable.swift` can improve readability.

## Potential issue

At line 118 and line 154 in `NVActivityIndicatorShape.swift `:
`lineWidth` is set to 2, instead of using variable `lineWidth` declared earlier in the scope.

## More customization supports

1. Users should be able to customize builtin shapes' specific properties, such as lineWidth, inner paddings.
2. Users should be able to customize builtin animations' specific properties, such as speed, orientation.
3. Users should be able to associate their custom shapes with builtin animations, or custom animations with builtin shapes, or both to leverage this library's viewable and presenter functionalities.

**Comment by ninjaprox** [comment]
Thanks for your suggestions and thoughts. Feel free to create PR regarding Swift style and code refactor.

As for customization, I'm a bit conservative about it. The reason is that all current animations are preset with specs like speed, stroke width, and look good with these values. Moreover, it's the essence of this library, simple, good looking animations out of the box, and worry free about customization. Giving users too much freedom and choices often confuses them rather than helps. Possible customizable properties like color, padding are already supported. You can suggest anything else without touching too much animation specs.

That being said, it doesn't mean there won't be room for customization. One direction I already think of is making a framework to ease creating new animations, and it might be a complement library to this one, or as a creator of this one.

**Comment by lurui1029** [comment]
Thanks for your response. Fully understand👌. I'll only focus on code improvements. Closing the issue.
