### ISSUE TITLE
Change UI block container background

### ISSUE THREAD

**Issue by iDevid** [ninjaprox/NVActivityIndicatorView#96]
Can you permit to modify the Activity Container when using startAnimating() func?

**Comment by ninjaprox** [comment]
@iDevid: Could you elaborate more?

**Comment by iDevid** [comment]
The Activity Container when you use startAnimating() is only black opaque and you can't modify it

**Comment by barnaclejive** [comment]
@ninjaprox I think @iDevid is referring to the activityContainer background color - make it an optional UIColor attribute of ActivityData. Currently it is hardcoded to 50% alpha black. I could see cases where you would want it to be clear, opaque, or just some other translucent color.

Personally, I would use a clear color since my activities are short. The convenience of NVActivityIndicatorViewable is great, but the full-screen 50% black is jarring in an otherwise mostly white colored app. I know how to use DEFAULT_BLOCKER_DISPLAY_TIME_THRESHOLD to avoid showing it for short activities, but it can't avoid flashing the black background in cases where the activity lasts just slightly longer than the threshold, and I'd rather not use DEFAULT_BLOCKER_MINIMUM_DISPLAY_TIME to artificially extend the amount of time the user has to wait.

**Comment by ninjaprox** [comment]
@barnaclejive: Thanks for clarification. It makes sense to have this to make the library more flexible.
